### ISSUE TITLE
force thumbnail view

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#5]
For what i care that option can go. I see no benefit for it or perhaps i am missing something

**Comment by dersphere** [comment]
XBMC stores (and restores) the last view mode id for each path. So if we only have one scraper we only have one relevant view where thumbnail view would be forced - but after setting it once manually, it would be stored and restored by xbmc anyway.

So with only scraper you are right (if the user sets thumbnail view once). I would suggest letting it in because it doesn't harm and could be disabled manually.

**Comment by MartijnKaijser** [comment]
I would choose for disabling it on default

**Comment by dersphere** [comment]
I guess more people want thumbnail view and are either lazy or just don't know how to switch than people which would disable this.

Your thoughts?

**Comment by MartijnKaijser** [comment]
Problem is that if they switch to another view and restart the plugin that it will be forced to thumbnail again
(was very annoying from my own experience and for some colleagues of mine) 
This makes sence for plugin like youtube but these are movie trailers for which we have movie posters.
Thumbnails doesn't really fit.
I would be more tempted to change it to force posters view.

**Comment by dersphere** [comment]
ok, then change to disabled by default.

Changing to some other view won't work or at least not easy - it was already a mess to find the corresponding view IDs for each skin. I doubt that there is another view which is similar between all skins.

**Comment by MartijnKaijser** [comment]
already had it set to false apparently  so time ago :P
